/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.9.1.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as addNote from "../addNote";
import type * as common from "../common";
import type * as deleteNote from "../deleteNote";
import type * as getNotes from "../getNotes";
import type * as getPastQuestions from "../getPastQuestions";
import type * as storePastQuestions from "../storePastQuestions";
import type * as storeUser from "../storeUser";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  addNote: typeof addNote;
  common: typeof common;
  deleteNote: typeof deleteNote;
  getNotes: typeof getNotes;
  getPastQuestions: typeof getPastQuestions;
  storePastQuestions: typeof storePastQuestions;
  storeUser: typeof storeUser;
}>;
